// 数据文件：FIB 单词、WFD 句子、WFD 每个词的中文
const FIB_WORDS = [
  [1, "introduced", "引入；介绍"],
  [2, "modes", "方式；模式"],
  [3, "ferry", "渡轮"],
  [4, "store", "商店；储存"],
  [5, "traveling", "旅行"],
  [6, "bored", "无聊的"],
  [7, "five", "五"],
  [8, "twenty-six", "二十六"],
  [9, "irrelevant", "无关的"],
  [10, "mysterious", "神秘的"],
  [11, "sources", "来源"],
  [12, "church", "教堂"],
  [13, "gaps", "差距；空白"],
  [14, "planet", "行星；地球"],
  [15, "green", "绿色的；环保的"],
  [16, "warmer", "更暖的"],
  [17, "industrial", "工业的"],
  [18, "distinctive", "独特的"],
  [19, "city", "城市"],
  [20, "matchstick", "火柴棍"],
  [21, "portraits", "肖像"],
  [22, "restricted", "受限制的"],
  [23, "incredibly", "难以置信地"],
  [24, "aspects", "方面"],
  [25, "biology", "生物学"],
  [26, "visible", "可见的"],
  [27, "powered", "以…为动力的"],
  [28, "urgency", "紧迫性"],
  [29, "sleek", "时髦流线型的"],
  [30, "hydrogen", "氢"],
  [31, "graduate", "毕业生；毕业"],
  [32, "sculpture", "雕塑"],
  [33, "real", "真实的"],
  [34, "incorporating", "融入；包含"],
  [35, "profession", "职业"],
  [36, "biggest", "最大的"],
  [37, "people", "人们"],
  [38, "throwing", "扔；投掷"],
  [39, "teams", "团队"],
  [40, "started", "开始"],
  [41, "frequently", "经常"],
  [42, "styles", "风格"],
  [43, "farms", "农场"],
  [44, "fresh", "新鲜的"],
  [45, "box", "盒子"],
  [46, "consume", "消耗；食用"],
  [47, "recommended", "推荐的"],
  [48, "diagnosed", "被诊断"],
  [49, "offensive", "冒犯的"],
  [50, "underground", "地下的"],
  [51, "pricing", "定价"],
  [52, "expensive", "昂贵的"],
  [53, "subsidies", "补贴"],
  [54, "average", "平均的"],
  [55, "serious", "严重的"],
  [56, "negative", "负面的"],
  [57, "risks", "风险"],
  [58, "journalist", "记者"],
  [59, "agency", "机构；代理"],
  [60, "experience", "经验；经历"],
  [61, "scary", "吓人的"],
  [62, "electronics", "电子产品"],
  [63, "cares", "关心"],
  [64, "respond", "回应；反应"],
  [65, "experimental", "实验性的"],
  [66, "prediction", "预测"],
  [67, "profound", "深远的"],
  [68, "consumption", "消耗；消费"],
  [69, "inviting", "诱人的；邀请"],
  [70, "requiring", "需要"],
  [71, "desk", "桌子"],
  [72, "regular", "定期的；常规的"],
  [73, "new", "新的"],
  [74, "restaurant", "餐厅"],
  [75, "menu", "菜单"],
  [76, "interesting", "有趣的"],
  [77, "owner", "老板；主人"],
  [78, "downtown", "市中心"],
  [79, "boost", "促进；提升"],
  [80, "climate", "气候"],
  [81, "development", "发展"],
  [82, "professional", "专业的"],
  [83, "placement", "实习；安置"],
  [84, "simple", "简单的"],
  [85, "sugar", "糖"],
  [86, "rush", "匆忙；激增"],
  [87, "steady", "稳定的"],
  [88, "workflow", "工作流程"],
  [89, "personalities", "性格；名人"],
  [90, "color", "颜色"],
  [91, "value", "价值"],
  [92, "attract", "吸引"],
  [93, "active", "活跃的"],
  [94, "completely", "完全地"],
  [95, "statistics", "统计数据"],
  [96, "every", "每个"],
  [97, "huge", "巨大的"],
  [98, "face", "面对；脸"],
  [99, "shadow", "影子"],
  [100, "ocean", "海洋"],
  [101, "shallow", "浅的"],
  [102, "depth", "深度"],
  [103, "infrastructure", "基础设施"],
  [104, "floor", "地面；海底"],
  [105, "career", "职业生涯"],
  [106, "culture", "文化"],
  [107, "cooperation", "合作"],
  [108, "expected", "预期的"],
  [109, "busy", "忙碌的"],
  [110, "instructor", "教练；讲师"],
  [111, "ability", "能力"],
  [112, "puffin", "海鹦"],
  [113, "allows", "允许"],
  [114, "predators", "捕食者"],
  [115, "collaborate", "合作"],
  [116, "corporate", "公司的"],
  [117, "safe", "安全的"],
  [118, "conception", "构想；概念"],
  [119, "sociable", "善于交际的"],
  [120, "obese", "肥胖的"],
  [121, "nutritional", "营养的"],
  [122, "consumers", "消费者"],
  [123, "generous", "慷慨的"],
  [124, "participant", "参与者"],
  [125, "invest", "投资"],
  [126, "concluded", "得出结论"],
  [127, "cultural", "文化的"],
  [128, "bringing", "带来"],
  [129, "complex", "复杂的"],
  [130, "work", "工作"],
  [131, "transport", "交通；运输"],
  [132, "daily", "每日的"],
  [133, "affordable", "负担得起的"],
  [134, "burgeon", "迅速发展"],
  [135, "systems", "系统"],
  [136, "contribution", "贡献"],
  [137, "reality", "现实"],
  [138, "jobs", "工作岗位"],
  [139, "apply", "申请；应用"],
  [140, "same", "相同的"],
  [141, "favorite", "最喜欢的"],
  [142, "hours", "小时；时间"],
  [143, "section", "部分"],
  [144, "factor", "因素"],
  [145, "qualification", "资格；学历"],
  [146, "energy", "能源；精力"],
  [147, "distribute", "分发；分配"],
  [148, "orientation", "方向；入职培训"],
  [149, "urgent", "紧急的"],
  [150, "system", "系统"],
  [151, "sector", "行业；部门"],
  [152, "throughout", "遍及；自始至终"],
  [153, "made", "制作"],
  [154, "absorb", "吸收"],
  [155, "everywhere", "到处"],
  [156, "sustainable", "可持续的"],
  [157, "application", "应用；申请"],
  [158, "benefit", "好处；受益"],
  [159, "humans", "人类"],
  [160, "common", "常见的"],
  [161, "opportunity", "机会"],
  [162, "operate", "操作；运营"],
  [163, "precision", "精确"],
  [164, "craftsmen", "工匠"],
  [165, "carpenter", "木匠"],
  [166, "legacy", "遗产"],
  [167, "practice", "做法；练习"],
  [168, "conspicuous", "显眼的"],
  [169, "cemetery", "墓地"],
  [170, "excavation", "挖掘"],
  [171, "chambers", "墓室；房间"],
  [172, "reference", "参考；提及"],
  [173, "habitable", "适合居住的"],
  [174, "source", "来源"],
  [175, "organic", "有机的"],
  [176, "material", "材料"],
  [177, "commitment", "承诺；投入"],
  [178, "permeate", "渗透；弥漫"],
  [179, "specifics", "细节"],
  [180, "eliminate", "消除"],
  [181, "population", "人口；种群"],
  [182, "levels", "水平"],
  [183, "challenge", "挑战"],
  [184, "rarely", "很少"],
  [185, "cast", "演员阵容；投射"],
  [186, "authors", "作者"],
  [187, "employee", "员工"],
  [188, "conducted", "进行；实施"],
  [189, "determination", "决心"],
  [190, "passions", "热情；爱好"],
  [191, "patience", "耐心"],
  [192, "mobile", "移动的；手机"],
  [193, "daughter", "女儿"],
  [194, "hygiene", "卫生"],
  [195, "childhood", "童年"],
  [196, "respiratory", "呼吸的"],
  [197, "explore", "探索"],
  [198, "plain", "平原；朴素的"],
  [199, "stick", "坚持；棍子"],
  [200, "technologies", "技术"],
  [201, "compatible", "兼容的"],
  [202, "products", "产品"],
  [203, "fundamental", "基本的"],
  [204, "understanding", "理解"],
  [205, "depictions", "描绘"],
  [206, "repetition", "重复"],
  [207, "curious", "好奇的"],
  [208, "extensive", "广泛的"],
  [209, "original", "原创的；最初的"],
  [210, "combination", "组合"],
  [211, "identifies", "识别"],
  [212, "phenomena", "现象"],
  [213, "macromolecular", "大分子的"],
  [214, "structures", "结构"],
  [215, "loosely", "松散地"],
  [216, "unashamedly", "毫不掩饰地"],
  [217, "habitat", "栖息地"],
  [218, "concepts", "概念"],
  [219, "socialize", "社交"],
  [220, "natural", "自然的"],
  [221, "academics", "学者；学术"],
  [222, "foreshadowed", "预示"],
  [223, "regions", "地区"],
  [224, "beleaguered", "困境重重的"],
  [225, "predicament", "困境"]];

const WFD_SENTENCES = [
  [1, "All of the assignments must be submitted in person to the faculty office.", "所有作业都必须亲自交到学院办公室。"],
  [2, "The nation achieved prosperity by opening its ports for trade.", "这个国家通过开放港口进行贸易而实现了繁荣。"],
  [3, "Traffic is the main cause of pollution in many cities.", "交通是许多城市污染的主要原因。"],
  [4, "We can't consider an increase in our price at this stage.", "现阶段我们不考虑提价。"],
  [5, "The bus to London will leave ten minutes later than planned.", "去伦敦的巴士将比计划晚十分钟出发。"],
  [6, "Understanding visual media has never been more challenging.", "如今，理解视觉媒体比以往任何时候都更具挑战性。"],
  [7, "Online courses allow students to work at their own pace.", "在线课程让学生可以按照自己的进度学习。"],
  [8, "Mechanical engineering first became prominent during the Industrial Revolution.", "机械工程在工业革命期间首次变得举足轻重。"],
  [9, "The digital revolution has changed the way we read.", "数字革命改变了我们阅读的方式。"],
  [10, "At that time, few people moved from the town to the village.", "那时，很少有人从城镇搬到村庄。"],
  [11, "Rail transport is becoming more and more popular.", "铁路运输正变得越来越受欢迎。"],
  [12, "Before architecture was invented, humans lived in underground houses.", "在建筑发明之前，人类居住在地下房屋里。"],
  [13, "The falling birth rate means the number of students drops.", "出生率下降意味着学生人数减少。"],
  [14, "The employment opportunities available in engineering are increasing rapidly.", "工程领域的就业机会正在迅速增加。"],
  [15, "The university canteen now offers many healthy meal options.", "大学食堂现在提供多种健康的餐食选择。"],
  [16, "Communication skills have become more important in recent years.", "近年来，沟通技能变得越来越重要。"],
  [17, "Before the invention of the refrigerator, people stored food in underground ice houses.", "在冰箱发明之前，人们把食物储存在地下冰窖里。"],
  [18, "You can keep your bags in the back room.", "你们可以把包放在后面的房间里。"],
  [19, "Please turn off the light to save energy.", "请关灯以节约能源。"],
  [20, "Before preparing any food, be sure to wash your hands well.", "准备任何食物前，务必将双手洗干净。"],
  [21, "Please move us to the meeting room for the next hour.", "请把我们带到会议室，接下来一个小时我们待在那里。"],
  [22, "The students will meet their new teachers after the summer vacation.", "暑假结束后，学生们将见到他们的新老师。"],
  [23, "Please close the door behind you when you leave the room.", "当你离开房间时，请随手关门。"],
  [24, "You must call your doctor to make an appointment.", "你必须打电话给你的医生预约。"],
  [25, "The restaurants are down the hall and to the right.", "餐厅在大厅尽头，往右拐。"],
  [26, "You can get your coffee and tea in the lounge.", "你可以在休息室喝到咖啡和茶。"],
  [27, "The teacher explained the homework to the class.", "老师向全班讲解了家庭作业。"],
  [28, "The fiction books are just past the counter.", "小说类书籍就在柜台那边。"],
  [29, "In my opinion, this car should be repaired soon.", "依我看，这辆车应该尽快修理。"],
  [30, "There was a lot of traffic this morning.", "今天早上路上车很多。"],
  [31, "The professor will have a lecture in the class.", "教授将在课堂上做讲座。"],
  [32, "Her design incorporates the best aspects of vernacular architecture.", "她的设计融合了乡土建筑的最佳特色。"],
  [33, "Your boss wants you to finish this report by Monday.", "你的老板要你在周一之前完成这份报告。"],
  [34, "All students are allowed to take the notes from the library.", "所有学生都可以从图书馆带走笔记。"],
  [35, "Undergraduate students can apply for the new biology course.", "本科生可以申请新的生物学课程。"],
  [36, "At this time experts are not able to analyze the effects of the new policy.", "目前，专家们还无法分析新政策的影响。"],
  [37, "The lecture will deal with the influence of technology on music.", "讲座将探讨技术对音乐的影响。"],
  [38, "A university degree is a requirement to enter many professions.", "许多职业都要求从业者拥有大学学位。"],
  [39, "You should complete the job application form in order to get called for the manager's position.", "你应该填写求职申请表，才能接到经理职位的面试通知。"],
  [40, "You must wear a hard hat on the construction site.", "在建筑工地上必须佩戴安全帽。"],
  [41, "When you attend a job interview, punctuality is the key.", "参加求职面试时，守时是关键。"],
  [42, "You are trained to be a specialized journalist.", "你受训成为一名专业记者。"],
  [43, "Stock predictions can be very capricious even for professionals.", "股票预测变幻莫测，即便是专业人士也很难准确把握。"],
  [44, "The new classrooms will be put into use next month.", "新教室将于下个月投入使用。"],
  [45, "You need to pass the written exam for the driver's license.", "你需要通过驾照的笔试。"],
  [46, "Football is played all year at the university.", "这所大学全年都有人踢足球。"],
  [47, "If you have any questions about the exam, please raise your hand.", "如果你对考试有任何问题，请举手。"],
  [48, "Social policy is a study of the government's social response to social issues.", "社会政策研究的是政府对社会问题所作出的社会回应。"],
  [49, "Assignments must be submitted at the end of the term.", "作业必须在学期结束时提交。"],
  [50, "Students can find news about climate change.", "学生可以找到有关气候变化的新闻。"],
  [51, "The staff is cleaning the room for tomorrow morning's meeting.", "工作人员正在打扫房间，为明天早上的会议做准备。"],
  [52, "Some studies show the link between depression and social media.", "一些研究表明抑郁症与社交媒体之间存在关联。"],
  [53, "Mental health professionals are talking about the topic of vulnerability.", "心理健康专业人士正在探讨脆弱性这一话题。"],
  [54, "Gold is a metal that appears naturally in a pure state.", "金是一种天然以纯态存在的金属。"],
  [55, "Creativity is more important for undergraduates.", "创造力对本科生来说更为重要。"],
  [56, "Social media is responsible for helping the government to solve social problems.", "社交媒体在帮助政府解决社会问题方面发挥了作用。"],
  [57, "For the purpose of research, data should be collected and analyzed.", "为开展研究，应收集并分析数据。"],
  [58, "The population will shrink drastically over the next twenty years.", "未来二十年内，人口将大幅减少。"],
  [59, "Computers used to be larger than they are now.", "计算机过去比现在大。"],
  [60, "The best student has an opportunity to acquire a scholarship.", "最优秀的学生有机会获得奖学金。"],
  [61, "Students must wear protective clothing provided in the medical laboratory.", "学生必须在医学实验室内穿戴所提供的防护服。"],
  [62, "The timetable for the next term will be available next week.", "下学期的课程表将于下周公布。"],
  [63, "Currently the growth of the economy is unpredictable.", "目前经济增长难以预测。"],
  [64, "Students live in the hall of residence during term time.", "学生在学期期间住在学校宿舍。"],
  [65, "All laboratory equipment will be provided in class.", "课堂上会提供所有实验室设备。"],
  [66, "Today we have a guest speaker who is visiting from Canada.", "今天我们有一位来自加拿大的嘉宾演讲者。"],
  [67, "Now you are able to download instructions and related videos below.", "现在你可以下载下方的说明和相关视频了。"],
  [68, "Please make an appointment with your tutor about work.", "请与你的导师预约讨论工作事宜。"],
  [69, "While some people regard it as reforming zeal, others regard it as recklessness.", "有些人认为这是改革热情，另一些人则认为这是鲁莽。"],
  [70, "Students of the first year usually live on campus.", "一年级学生通常住在校园内。"],
  [71, "A good academic paper should present a clear argument.", "一篇好的学术论文应当提出清晰的论点。"],
  [72, "We are committed to recruiting candidates from all backgrounds and identities.", "我们致力于招募来自各种背景和身份的候选人。"],
  [73, "You can borrow eight books from the library at a time.", "你每次可以从图书馆借八本书。"],
  [74, "The subject is complex and difficult to explain.", "这个话题很复杂，难以解释。"],
  [75, "Joining a society can help to meet new people.", "加入社团有助于结识新朋友。"],
  [76, "Exam results will be published on the notice board.", "考试成绩将公布在布告栏上。"],
  [77, "Being a vegan means not consuming any animal products.", "成为纯素食者意味着不食用任何动物产品。"],
  [78, "You should meet me in the lecture theater room.", "你到演讲厅来找我吧。"],
  [79, "You should submit your term papers to the general office.", "你们应该把学期论文交到总办公室。"],
  [80, "The seminar on writing skills has been cancelled.", "写作技能研讨会已取消。"],
  [81, "The earth's atmosphere is primarily composed of oxygen and nitrogen gases.", "地球大气主要由氧气和氮气组成。"],
  [82, "Students are required to have an undergraduate degree in biology to be enrolled in this course.", "学生必须持有生物学本科学位，才能选修这门课程。"],
  [83, "There will be a guest lecturer in the next class.", "下节课会有一位客座讲师。"],
  [84, "Our culture influences the choices we make.", "我们的文化影响着我们所做的选择。"],
  [85, "Atoms are the basic building blocks of matter.", "原子是物质的基本组成单位。"],
  [86, "A world-renowned expert on financial management will give a guest lecture.", "一位世界知名的金融管理专家将发表客座讲座。"],
  [87, "The weather used to be lovely for this time of year.", "往年这个时候天气通常很好。"],
  [88, "I want to make an appointment with the manager.", "我想和经理预约一下。"],
  [89, "The stairs are to the left of the elevator.", "楼梯在电梯左侧。"],
  [90, "There is an accounting assignment for finance students.", "金融专业学生有一项会计作业。"],
  [91, "Food containing ample calories provides little or no nutritional value.", "高热量食物很少或者根本没有营养价值。"],
  [92, "You will get your uniform on the first day.", "你会在第一天拿到你的制服。"],
  [93, "We should have a meeting to discuss and report.", "我们应该开个会讨论并汇报。"],
  [94, "The restrooms are down the entrance and to the right.", "洗手间在入口处往下走，然后向右拐。"],
  [95, "Time is needed to complete the lecture.", "完成这次讲座需要时间。"],
  [96, "The paper has the potential to transform life science.", "这篇论文有可能改变生命科学领域。"],
  [97, "At that time, few people moved from towns to villages.", "那时，很少有人从城镇搬到乡村。"],
  [98, "Many cities are actively working on ways to reduce air pollution.", "许多城市正在积极寻求减少空气污染的方法。"],
  [99, "Sympathy is a feeling of sorrow for someone who is not happy.", "同情是对不快乐的人感到悲伤的一种情感。"],
  [100, "An academic essay should use evidence from both primary and secondary sources.", "学术论文应同时使用一手资料和二手资料中的证据。"],
  [101, "A surprisingly large number of students applied for that course.", "申请那门课程的学生数量惊人地多。"],
  [102, "It is an integrated course with several main elements.", "这是一门综合性课程，包含几个主要部分。"],
  [103, "The internet has transformed the nature of publishing.", "互联网已彻底改变了出版的性质。"],
  [104, "Scholarships are available for both local and international students.", "本地学生和国际学生均可申请奖学金。"],
  [105, "All students have their own styles of learning.", "所有学生都有自己的学习风格。"],
  [106, "It is interesting to observe the development of the language skills of toddlers.", "观察幼儿语言技能的发展是很有趣的。"],
  [107, "When the root system of a plant fails, foliage suffers.", "当植物的根系受损时，枝叶也会跟着遭殃。"],
  [108, "The school canteen sells a large variety of water and food.", "学校食堂出售种类繁多的水和食物。"],
  [109, "The skills of great stage actors cannot be taught.", "伟大舞台演员的技巧是无法传授的。"],
  [110, "The history department is very active in research.", "历史系在科研方面非常活跃。"],
  [111, "The digital camera has some advantages over traditional film.", "数码相机比传统胶片有一些优势。"],
  [112, "A visit to the designed museum is of great value.", "参观这座设计博物馆很有价值。"],
  [113, "Honey can be used as food and a health product.", "蜂蜜可以用作食品和保健品。"],
  [114, "The course involves a combination of pure and applied mathematics.", "这门课程综合了纯数学与应用数学。"],
  [115, "Designers need to keep up with social trends.", "设计师需要跟上社会潮流。"],
  [116, "Academic libraries across the world are steadily incorporating social media.", "世界各地的学术图书馆正逐步将社交媒体融入自身工作中。"],
  [117, "Air pollution is a serious problem all over the world.", "空气污染是全世界面临的严重问题。"],
  [118, "Sugar is a compound including carbon, hydrogen and oxygen atoms.", "糖是一种包含碳、氢和氧原子的化合物。"],
  [119, "The researchers are disappointed that the results of the research have been proved to be inconclusive.", "研究人员感到失望，因为研究结果被证明没有定论。"],
  [120, "Journalism faces a crisis in light of the digital revolution.", "面对数字革命，新闻业正面临危机。"],
  [121, "Being bilingual does not necessarily mean having the ability to analyze the languages.", "会说双语并不一定意味着具备分析语言的能力。"],
  [122, "We can all meet at my office after the lecture.", "讲座结束后，我们都可以到我的办公室见个面。"],
  [123, "The university has invested in the new technology designed to support learning.", "该大学已投资于这项旨在支持学习的新技术。"],
  [124, "The area has a wide variety of underwater habitats and species.", "该区域拥有种类繁多的水下栖息地和物种。"],
  [125, "Students should leave their bags on the tables by the door.", "学生们应该把包留在门边的桌子上。"],
  [126, "Scientists recognize different ice types according to the water molecule content.", "科学家根据水分子含量来区分不同的冰类型。"],
  [127, "Firm conclusions can be established through rigorous experiments.", "通过严谨的实验，可以得出可靠的结论。"],
  [128, "The library will be closed for staff training tomorrow morning.", "明天上午图书馆因员工培训将闭馆。"],
  [129, "All medical students must clean their hands before entering the room.", "所有医学生在进入房间前都必须洗手。"],
  [130, "You should provide examples to support your ideas and arguments.", "你应该举例来支持你的观点和论点。"],
  [131, "Speak to your tutor if you need further assistance.", "如需更多帮助，请与你的导师联系。"],
  [132, "The history lecture has been moved to the lecture theater.", "历史讲座已改在阶梯教室举行。"],
  [133, "They developed a unique approach to training their employees.", "他们开发了一种独特的员工培训方法。"],
  [134, "We have a lecture in the morning on Thursday.", "我们周四上午有一场讲座。"],
  [135, "The new media have transcended traditional national boundaries.", "新媒体已经超越了传统的国家边界。"],
  [136, "Everyone in this room needs to follow the rules.", "这个房间里的每个人都需要遵守规则。"],
  [137, "I thought it was through the small meeting room.", "我以为是通过那间小会议室。"],
  [138, "The history of the university is a long and interesting one.", "这所大学的历史悠久而有趣。"],
  [139, "The opening hours of the library are reduced during summer.", "夏季图书馆的开放时间缩短了。"],
  [140, "There is a significant difference between theory and practice in education.", "教育中理论与实践之间存在显著差异。"],
  [141, "Universities need to secure the grants for research projects.", "大学需要为研究项目争取到资助。"],
  [142, "There will be a meeting for the first-year students on Friday.", "周五将举行一场大一新生会议。"],
  [143, "The teacher training includes observing the classes.", "教师培训包括观摩课堂。"],
  [144, "The Industrial Revolution in Europe was driven by steam technology.", "欧洲工业革命由蒸汽技术推动。"],
  [145, "Students who study overseas can significantly improve their employment opportunities.", "出国留学的学生能显著提升自己的就业机会。"],
  [146, "Strangely, people are simultaneously impressed by and skeptical of statistics.", "奇怪的是，人们对统计数据既印象深刻，又心存怀疑。"],
  [147, "The science library is currently located on the ground floor.", "科学图书馆目前位于底层。"],
  [148, "Our courses help to improve critical thinking and independent learning skills.", "我们的课程有助于提升批判性思维和独立学习能力。"],
  [149, "Continuing students will be sent necessary application forms.", "继续就读的学生将收到必要的申请表。"],
  [150, "Check the website if you are looking for discounted textbooks.", "如果你想找打折的教科书，可以查看网站。"],
  [151, "You should draw your graph on a separate page.", "你应该把图形画在单独的页面上。"],
  [152, "Water filters on campus will discourage the unnecessary use of plastic bottles.", "校园内的饮水过滤器将减少不必要的塑料瓶使用。"],
  [153, "There is a pharmacy on campus near the bookstore.", "校园里书店附近有一家药店。"],
  [154, "The teacher asked the group to commence the task.", "老师要求小组开始这项任务。"],
  [155, "The island is located at the south end of the bay.", "该岛位于海湾南端。"],
  [156, "The professor took a year off to work on her book.", "教授休假一年来写她的书。"],
  [157, "The railway makes long-distance travel possible for everyone.", "铁路使每个人都能进行长途旅行。"],
  [158, "Sales figures for last year were better than expected.", "去年的销售数据好于预期。"],
  [159, "Students are advised to use multiple methods for this project.", "建议学生在本项目中使用多种方法。"],
  [160, "She began by giving an outline of the previous lecture.", "她一开始先概述了上一讲的内容。"],
  [161, "The new camera can identify your eyes and focus on them.", "这款新相机可以识别你的眼睛并对其进行对焦。"],
  [162, "The article refers to a number of very interesting experiments.", "这篇文章提到了一系列非常有趣的实验。"],
  [163, "Our aim is to reduce the risks that people take.", "我们的目标是降低人们所冒的风险。"],
  [164, "Students intending to go to the conference must register now.", "打算参加会议的学生现在必须注册。"],
  [165, "Radio is one of the most popular forms of entertainment throughout the world.", "广播是全世界最受欢迎的娱乐形式之一。"],
  [166, "The dance department stages elaborate performances each semester.", "舞蹈系每学期都会呈上精心编排的演出。"],
  [167, "It is hard to observe the reaction of the character.", "很难观察到角色的反应。"],
  [168, "I thought we would meet in the small meeting room.", "我原以为我们会在小会议室见面。"],
  [169, "Hundreds of scientific papers have been published on global warming.", "关于全球变暖的科学论文已有数百篇。"],
  [170, "Please check the information on the website for the opening time.", "请查看网站上的开放时间信息。"],
  [171, "Organizational failure is considered from various perspectives in academic literature.", "学术文献从多个视角对组织失败进行了探讨。"],
  [172, "It is really a comprehensive program covering both theory and practice.", "这确实是一个涵盖理论与实践两方面的综合项目。"],
  [173, "I will come back to this in a moment.", "关于这一点，我稍后会再谈。"],
  [174, "He has landed a job in a very prestigious law firm.", "他在一家非常有声望的律师事务所找到了一份工作。"],
  [175, "Parents are financially responsible for their children right up until they reach adulthood.", "父母对子女负有经济抚养责任，直至子女成年。"],
  [176, "Packaging is very important to attract the attention of a buyer.", "包装对于吸引购买者的注意力非常重要。"],
  [177, "The archeologist's new discoveries stand out in the previously overlooked foundations.", "这位考古学家的新发现，在那些此前被忽视的基址中格外突出。"],
  [178, "Let me give you an example to explain what I mean.", "让我给你举个例子来说明我的意思。"],
  [179, "Many birds migrate to warmer areas for the winter.", "许多鸟类会迁徙到较温暖的地区过冬。"],
  [180, "A good academic paper should be clear.", "一篇好的学术论文应当清晰明了。"],
  [181, "Although sustainable development is not easy, it is an unavoidable responsibility.", "虽然可持续发展并非易事，但这是一项不可回避的责任。"],
  [182, "A good architectural structure should be useful, durable, and beautiful.", "好的建筑结构应当实用、耐用且美观。"],
  [183, "Collaboration between departments is a feature of successful companies.", "部门之间的协作是成功企业的特征。"],
  [184, "Every student has both the right and the ability to succeed.", "每个学生都既有权利也有能力取得成功。"],
  [185, "Certain scientific principles must be learned verbally or by a logical deduction.", "某些科学原理必须通过口头讲解或逻辑推理来学习。"]];

const WORD_ZH = {"a": "一个", "ability": "能力", "able": "能够", "about": "关于", "academic": "学术的", "according": "根据", "accounting": "会计", "achieved": "实现", "acquire": "获得", "across": "遍及", "active": "活跃的", "actively": "积极地", "actors": "演员", "adulthood": "成年", "advantages": "优势", "advised": "建议", "after": "在…之后", "aim": "目标", "air": "空气", "all": "所有", "allow": "让；允许", "allowed": "被允许", "although": "虽然", "ample": "大量的", "an": "一个", "analyze": "分析", "analyzed": "分析", "and": "和", "animal": "动物", "any": "任何", "appears": "出现；存在", "application": "申请", "applied": "应用的", "apply": "申请", "appointment": "预约", "approach": "方法", "archeologist's": "考古学家的", "architectural": "建筑的", "architecture": "建筑", "are": "是", "area": "区域", "areas": "地区", "argument": "论点", "arguments": "论点", "article": "文章", "as": "作为", "asked": "要求", "aspects": "方面", "assignment": "作业", "assignments": "作业", "assistance": "帮助", "at": "在", "atmosphere": "大气", "atoms": "原子", "attend": "参加", "attention": "注意力", "attract": "吸引", "available": "可获得的", "back": "后面的", "backgrounds": "背景", "bags": "包", "basic": "基本的", "bay": "海湾", "be": "是", "beautiful": "美观的", "became": "变得", "become": "变得", "becoming": "正变得", "been": "是（过去分词）", "before": "在…之前", "began": "开始", "behind": "在…后面", "being": "作为；是", "below": "下方", "best": "最好的", "better": "更好的", "between": "在…之间", "bilingual": "双语的", "biology": "生物学", "birds": "鸟", "birth": "出生", "blocks": "组成单位", "board": "栏；板", "book": "书", "books": "书", "bookstore": "书店", "borrow": "借", "boss": "老板", "both": "两者都", "bottles": "瓶子", "boundaries": "边界", "building": "组成", "bus": "巴士", "buyer": "购买者", "by": "通过；在…之前", "call": "打电话", "called": "被叫去", "calories": "卡路里", "camera": "相机", "campus": "校园", "can": "可以", "can't": "不能", "canada": "加拿大", "cancelled": "取消", "candidates": "候选人", "cannot": "不能", "canteen": "食堂", "capricious": "变幻莫测的", "car": "车", "carbon": "碳", "cause": "原因", "certain": "某些", "challenging": "有挑战性的", "change": "变化", "changed": "改变", "character": "角色", "check": "查看", "children": "子女", "choices": "选择", "cities": "城市", "class": "课堂；班级", "classes": "课堂", "classrooms": "教室", "clean": "清洁", "cleaning": "打扫", "clear": "清晰的", "climate": "气候", "close": "关", "closed": "关闭", "clothing": "服装", "coffee": "咖啡", "collaboration": "协作", "collected": "收集", "combination": "结合", "come": "回来", "commence": "开始", "committed": "致力于", "communication": "沟通", "companies": "公司", "complete": "完成；填写", "complex": "复杂的", "composed": "组成", "compound": "化合物", "comprehensive": "综合的", "computers": "计算机", "conclusions": "结论", "conference": "会议", "consider": "考虑", "considered": "探讨", "construction": "建筑施工", "consuming": "食用；消耗", "containing": "含有", "content": "含量", "continuing": "继续就读的", "counter": "柜台", "course": "课程", "courses": "课程", "covering": "涵盖", "creativity": "创造力", "crisis": "危机", "critical": "批判性的", "culture": "文化", "currently": "目前", "dance": "舞蹈", "data": "数据", "day": "天", "deal": "探讨", "deduction": "推理", "degree": "学位", "department": "系；部门", "departments": "部门", "depression": "抑郁症", "design": "设计", "designed": "设计的；旨在", "designers": "设计师", "developed": "开发", "development": "发展", "difference": "差异", "different": "不同的", "difficult": "困难的", "digital": "数字的", "disappointed": "失望的", "discounted": "打折的", "discourage": "减少；阻止", "discoveries": "发现", "discuss": "讨论", "doctor": "医生", "does": "助动词", "door": "门", "down": "沿着", "download": "下载", "drastically": "大幅地", "draw": "画", "driven": "推动", "driver's": "驾驶员的", "drops": "下降", "durable": "耐用的", "during": "在…期间", "each": "每个", "earth's": "地球的", "easy": "容易的", "economy": "经济", "education": "教育", "effects": "影响", "eight": "八", "elaborate": "精心的", "elements": "部分；要素", "elevator": "电梯", "employees": "员工", "employment": "就业", "end": "结束；尽头", "energy": "能源", "engineering": "工程", "enrolled": "注册入学", "enter": "进入", "entering": "进入", "entertainment": "娱乐", "entrance": "入口", "equipment": "设备", "essay": "论文", "established": "得出；建立", "europe": "欧洲", "even": "即使", "every": "每个", "everyone": "每个人", "evidence": "证据", "exam": "考试", "example": "例子", "examples": "例子", "expected": "预期", "experiments": "实验", "expert": "专家", "experts": "专家", "explain": "解释", "explained": "讲解", "eyes": "眼睛", "faces": "面临", "faculty": "学院", "fails": "失败；受损", "failure": "失败", "falling": "下降的", "feature": "特征", "feeling": "感情", "few": "很少", "fiction": "小说", "figures": "数据", "film": "胶片", "filters": "过滤器", "finance": "金融", "financial": "金融的", "financially": "经济上", "find": "找到", "finish": "完成", "firm": "可靠的；公司", "first": "第一", "first-year": "一年级的", "floor": "楼层", "focus": "对焦", "foliage": "枝叶", "follow": "遵守", "food": "食物", "football": "足球", "for": "为了", "form": "形式；表格", "forms": "表格；形式", "foundations": "基址；地基", "friday": "周五", "from": "从", "further": "更多的", "gases": "气体", "general": "总的", "get": "得到", "give": "给", "giving": "给出", "global": "全球的", "go": "去", "gold": "金", "good": "好的", "government": "政府", "government's": "政府的", "grants": "资助", "graph": "图表", "great": "伟大的", "ground": "底层；地面", "group": "小组", "growth": "增长", "guest": "客座的", "habitats": "栖息地", "hall": "大厅；宿舍楼", "hand": "手", "hands": "手", "happy": "快乐的", "hard": "难的；硬的", "has": "有", "hat": "帽子", "have": "有", "having": "拥有", "he": "他", "health": "健康", "healthy": "健康的", "help": "帮助", "helping": "帮助", "her": "她的", "history": "历史", "homework": "家庭作业", "honey": "蜂蜜", "hour": "小时", "hours": "时间", "houses": "房屋", "humans": "人类", "hundreds": "数百", "hydrogen": "氢", "i": "我", "ice": "冰", "ideas": "观点", "identify": "识别", "identities": "身份", "if": "如果", "important": "重要的", "impressed": "印象深刻的", "improve": "提高", "in": "在…里", "includes": "包括", "including": "包括", "inconclusive": "没有定论的", "incorporates": "融合", "incorporating": "融入", "increase": "增加", "increasing": "增加", "independent": "独立的", "industrial": "工业的", "influence": "影响", "influences": "影响", "information": "信息", "instructions": "说明", "integrated": "综合的", "intending": "打算", "interesting": "有趣的", "international": "国际的", "internet": "互联网", "interview": "面试", "into": "进入", "invented": "发明", "invention": "发明", "invested": "投资", "involves": "包含", "is": "是", "island": "岛", "issues": "问题", "it": "它", "its": "它的", "job": "工作", "joining": "加入", "journalism": "新闻业", "journalist": "记者", "just": "就", "keep": "放；保持", "key": "关键", "laboratory": "实验室", "landed": "找到（工作）", "language": "语言", "languages": "语言", "large": "大的", "larger": "更大的", "last": "去年的；最后的", "later": "晚", "law": "法律", "learned": "学习", "learning": "学习", "leave": "离开；留下", "lecture": "讲座", "lecturer": "讲师", "left": "左边", "let": "让", "libraries": "图书馆", "library": "图书馆", "license": "执照", "life": "生命", "light": "灯", "link": "关联", "literature": "文献", "little": "很少", "live": "居住", "lived": "居住", "local": "本地的", "located": "位于", "logical": "逻辑的", "london": "伦敦", "long": "长的", "long-distance": "长途的", "looking": "寻找", "lot": "很多", "lounge": "休息室", "lovely": "很好的", "main": "主要的", "make": "做；制定", "makes": "使", "management": "管理", "manager": "经理", "manager's": "经理的", "many": "许多", "mathematics": "数学", "matter": "物质", "me": "我", "meal": "餐", "mean": "意思", "means": "意味着", "mechanical": "机械的", "media": "媒体", "medical": "医学的", "meet": "见面", "meeting": "会议", "mental": "心理的", "metal": "金属", "methods": "方法", "migrate": "迁徙", "minutes": "分钟", "molecule": "分子", "moment": "片刻", "monday": "周一", "month": "月", "more": "更", "morning": "早上", "morning's": "早上的", "most": "最", "move": "带；移动", "moved": "搬；移动", "multiple": "多种", "museum": "博物馆", "music": "音乐", "must": "必须", "my": "我的", "nation": "国家", "national": "国家的", "naturally": "天然地", "nature": "性质", "near": "附近", "necessarily": "必然", "necessary": "必要的", "need": "需要", "needed": "需要", "needs": "需要", "never": "从未", "new": "新的", "news": "新闻", "next": "下一个", "nitrogen": "氮", "no": "没有", "not": "不", "notes": "笔记", "notice": "通知", "now": "现在", "number": "数量", "nutritional": "营养的", "observe": "观察", "observing": "观摩", "of": "…的", "off": "关；休假", "offers": "提供", "office": "办公室", "on": "在…上", "one": "一个", "online": "在线的", "opening": "开放；打开", "opinion": "看法", "opportunities": "机会", "opportunity": "机会", "options": "选择", "or": "或", "order": "为了（in order to）", "organizational": "组织的", "others": "其他人", "our": "我们的", "out": "出去", "outline": "概述", "over": "在…期间；比", "overlooked": "被忽视的", "overseas": "海外", "own": "自己的", "oxygen": "氧", "pace": "进度", "packaging": "包装", "page": "页", "paper": "论文", "papers": "论文", "parents": "父母", "pass": "通过", "past": "经过", "people": "人们", "performances": "演出", "person": "亲自（in person）", "perspectives": "视角", "pharmacy": "药店", "planned": "计划", "plant": "植物", "plastic": "塑料", "played": "踢；玩", "please": "请", "policy": "政策", "pollution": "污染", "popular": "受欢迎的", "population": "人口", "ports": "港口", "position": "职位", "possible": "可能的", "potential": "潜力", "practice": "实践", "predictions": "预测", "preparing": "准备", "present": "提出", "prestigious": "有声望的", "previous": "之前的", "previously": "先前", "price": "价格", "primarily": "主要地", "primary": "一手的", "principles": "原理", "problem": "问题", "problems": "问题", "product": "产品", "products": "产品", "professionals": "专业人士", "professions": "职业", "professor": "教授", "program": "项目", "project": "项目", "projects": "项目", "prominent": "重要的", "prosperity": "繁荣", "protective": "防护的", "proved": "被证明", "provide": "提供", "provided": "提供", "provides": "提供", "published": "发表；公布", "publishing": "出版", "punctuality": "守时", "pure": "纯的", "purpose": "目的", "put": "投入", "questions": "问题", "radio": "广播", "rail": "铁路", "railway": "铁路", "raise": "举起", "rapidly": "迅速地", "rate": "率", "reach": "达到", "reaction": "反应", "read": "阅读", "really": "确实", "recent": "最近的", "recklessness": "鲁莽", "recognize": "识别", "recruiting": "招募", "reduce": "减少", "reduced": "缩短；减少", "refers": "提到", "reforming": "改革的", "refrigerator": "冰箱", "regard": "认为", "register": "注册", "related": "相关的", "repaired": "修理", "report": "报告；汇报", "required": "被要求", "requirement": "要求", "research": "研究", "researchers": "研究人员", "residence": "宿舍", "response": "回应", "responsibility": "责任", "responsible": "负责的", "restaurants": "餐厅", "restrooms": "洗手间", "results": "结果", "revolution": "革命", "right": "右边；权利", "rigorous": "严谨的", "risks": "风险", "room": "房间", "root": "根", "rules": "规则", "sales": "销售", "save": "节约", "scholarship": "奖学金", "scholarships": "奖学金", "school": "学校", "science": "科学", "scientific": "科学的", "scientists": "科学家", "secondary": "二手的", "secure": "争取到", "sells": "出售", "semester": "学期", "seminar": "研讨会", "sent": "寄给", "separate": "单独的", "serious": "严重的", "several": "几个", "she": "她", "should": "应该", "show": "表明", "shrink": "减少", "significant": "显著的", "significantly": "显著地", "simultaneously": "同时", "site": "工地", "skeptical": "怀疑的", "skills": "技能", "small": "小的", "social": "社会的", "society": "社团", "solve": "解决", "some": "一些", "someone": "某人", "soon": "尽快", "sorrow": "悲伤", "sources": "来源；资料", "south": "南", "speak": "谈话", "speaker": "演讲者", "specialized": "专业的", "species": "物种", "staff": "员工", "stage": "阶段；舞台", "stages": "上演", "stairs": "楼梯", "stand": "突出（stand out）", "state": "状态", "statistics": "统计数据", "steadily": "逐步地", "steam": "蒸汽", "stock": "股票", "stored": "储存", "strangely": "奇怪的是", "structure": "结构", "student": "学生", "students": "学生", "studies": "研究", "study": "研究；学习", "styles": "风格", "subject": "话题", "submit": "提交", "submitted": "提交", "succeed": "成功", "successful": "成功的", "suffers": "受损", "sugar": "糖", "summer": "夏季", "support": "支持", "sure": "务必", "surprisingly": "惊人地", "sustainable": "可持续的", "sympathy": "同情", "system": "系统", "tables": "桌子", "take": "带走", "talking": "谈论", "task": "任务", "taught": "传授", "tea": "茶", "teacher": "老师", "teachers": "老师", "technology": "技术", "ten": "十", "term": "学期", "textbooks": "教科书", "than": "比", "that": "那；那个", "the": "这；那（定冠词）", "theater": "剧场；演讲厅", "their": "他们的", "them": "它们", "theory": "理论", "there": "那里", "they": "他们", "thinking": "思维", "this": "这个", "thought": "以为", "through": "通过", "throughout": "遍及", "thursday": "周四", "time": "时间", "timetable": "课程表", "to": "到；去", "today": "今天", "toddlers": "幼儿", "tomorrow": "明天", "took": "休（假）", "topic": "话题", "town": "城镇", "towns": "城镇", "trade": "贸易", "traditional": "传统的", "traffic": "交通", "trained": "受训", "training": "培训", "transcended": "超越", "transform": "改变", "transformed": "改变", "transport": "运输", "travel": "旅行", "trends": "潮流", "turn": "关（turn off）", "tutor": "导师", "twenty": "二十", "types": "类型", "unavoidable": "不可避免的", "undergraduate": "本科的", "undergraduates": "本科生", "underground": "地下的", "understanding": "理解", "underwater": "水下的", "uniform": "制服", "unique": "独特的", "universities": "大学", "university": "大学", "unnecessary": "不必要的", "unpredictable": "难以预测的", "until": "直到", "up": "直到（up until）", "us": "我们", "use": "使用", "used": "过去常常；被使用", "useful": "实用的", "usually": "通常", "vacation": "假期", "value": "价值", "variety": "种类", "various": "各种的", "vegan": "纯素食者", "verbally": "口头地", "vernacular": "乡土的", "very": "非常", "videos": "视频", "village": "村庄", "villages": "村庄", "visit": "参观", "visiting": "来访", "visual": "视觉的", "vulnerability": "脆弱性", "want": "想要", "wants": "想要", "warmer": "更温暖的", "warming": "变暖", "was": "是（过去式）", "wash": "洗", "water": "水", "way": "方式", "ways": "方法", "we": "我们", "wear": "穿戴", "weather": "天气", "website": "网站", "week": "周", "well": "好地", "were": "是（过去式）", "what": "什么", "when": "当…时", "while": "然而", "who": "…的人", "wide": "广泛的", "will": "将", "winter": "冬天", "with": "和；带有", "work": "工作；学习", "working": "努力", "world": "世界", "world-renowned": "世界知名的", "would": "会", "writing": "写作", "written": "书面的", "year": "年", "years": "年", "you": "你", "your": "你的", "zeal": "热情"};
